CREATE OR REPLACE TEMP VIEW clean_individual_contributions AS
SELECT
    TRY_CAST(SUB_ID AS BIGINT) AS SUB_ID,
    CMTE_ID AS TARGET_CMTE_ID,
    NAME AS CONTRIBUTOR_NAME,
    CITY,
    STATE,
    ZIP_CODE,
    EMPLOYER,
    OCCUPATION,
    TRY_CAST(TRANSACTION_AMT AS DECIMAL(14,2)) AS AMOUNT,
    TRY_STRPTIME(TRANSACTION_DT, '%m%d%Y')::DATE AS TRANSACTION_DT,
    TRANSACTION_TP,
    ENTITY_TP,
    OTHER_ID,
    IMAGE_NUM,
    FILE_NUM,
    TRAN_ID,
    MEMO_CD,
    MEMO_TEXT
FROM read_parquet('parquet_store/raw_indiv.parquet')
WHERE ENTITY_TP = 'IND'
  AND (MEMO_CD IS NULL OR MEMO_CD <> 'X');
